isc.Tree.create({
    ID:"docTree",
    nameProperty:"id",
    openProperty:"isOpen",
    showRoot:false,
    root:{
        name:"/",
        children:[
            {contentsURL:"[docRoot]SmartClient_Quick_Start_Guide.pdf", icon:"[SKIN]pdf.gif",
             id:"QuickStartGuide", title:"SmartClient QuickStart Guide"},
            {contentsURL:"[referenceRoot]SmartClient_Explorer.html", icon:"[SKIN]features.png",
             id:"FeatureExplorer", title:"Feature Explorer"},
            {icon:"[SKIN]cube_blue.gif", id:"featureExplorerOverview",
             ref:"group:featureExplorerOverview", title:"Feature Explorer Overview"},
            {
                isOpen:"true",
                title:"Concepts",
                children:[
                    {
                        title:"Client-Server Integration",
                        id:"2",
                        children:[
                            {id:"49", ref:"group:clientDataIntegration", icon:"[SKIN]cube_blue.gif",
                             title:"Client-side Data Integration"},
                            {id:"67", ref:"group:serverDataIntegration", icon:"[SKIN]cube_blue.gif",
                             title:"Server DataSource Integration"}
                        ],
                        icon:"[SKIN]cube_blue.gif",
                        ref:"group:clientServerIntegration"
                    },
                    {title:"SmartClient Architecture", id:"3", icon:"[SKIN]cube_blue.gif",
                     ref:"group:smartArchitecture"},
                    {title:"Debugging", id:"4", icon:"[SKIN]cube_blue.gif", ref:"group:debugging"},
                    {
                        title:"Deploying SmartClient",
                        id:"5",
                        icon:"[SKIN]cube_blue.gif",
                        ref:"group:iscInstall",
                        children:[
                            {id:"40", ref:"group:servletDetails", icon:"[SKIN]cube_blue.gif",
                             title:"The Core and Optional SmartClient servlets"},
                            {id:"41", ref:"group:javaModuleDependencies", icon:"[SKIN]cube_blue.gif",
                             title:"Java Module Dependencies"}
                        ]
                    },
                    {title:"Visual Builder", id:"6", icon:"[SKIN]cube_blue.gif",
                     ref:"group:visualBuilder"},
                    {title:".NET, PHP, Serverless Integration", id:"7", icon:"[SKIN]cube_blue.gif",
                     ref:"group:nonJavaBackend"},
                    {title:"Integration with Spring", id:"8", icon:"[SKIN]cube_blue.gif",
                     ref:"group:springIntegration"},
                    {title:"Integration with Hibernate", id:"9", icon:"[SKIN]cube_blue.gif",
                     ref:"group:hibernateIntegration"},
                    {title:"Integration with JSF", id:"10", icon:"[SKIN]cube_blue.gif",
                     ref:"group:jsfIntegration"},
                    {title:"Integration with Struts", id:"11", icon:"[SKIN]cube_blue.gif",
                     ref:"group:strutsIntegration"},
                    {
                        title:"Component XML",
                        id:"12",
                        icon:"[SKIN]cube_blue.gif",
                        ref:"group:componentXML",
                        children:[
                            {id:"35", ref:"group:componentSchema", icon:"[SKIN]cube_blue.gif",
                             title:"Component Schema"}
                        ]
                    },
                    {id:"29", ref:"group:mobileDevelopment", icon:"[SKIN]cube_blue.gif",
                     title:"Development for mobile devices"},
                    {id:"38", ref:"group:i18n", icon:"[SKIN]cube_blue.gif",
                     title:"Internationalization and Localization (i18n,l10n)"},
                    {id:"39", ref:"group:dataSourceLocalization", icon:"[SKIN]cube_blue.gif",
                     title:"DataSource Localization"},
                    {id:"42", ref:"group:jpaIntegration", icon:"[SKIN]cube_blue.gif",
                     title:"Integration with JPA"},
                    {id:"43", ref:"group:gaeIntegration", icon:"[SKIN]cube_blue.gif",
                     title:"Google Application Engine (GAE)"},
                    {id:"64", ref:"group:writeCustomDataSource", icon:"[SKIN]cube_blue.gif",
                     title:"Custom Server DataSources"},
                    {id:"65", ref:"group:featuresCustomPersistence", icon:"[SKIN]cube_blue.gif",
                     title:"Using SmartClient Server framework with custom persistence logic"},
                    {id:"66", ref:"group:sqlVsJPA", icon:"[SKIN]cube_blue.gif",
                     title:"SQL DataSource vs JPA, EJB, Ibatis and other technologies"},
                    {id:"76", ref:"group:dateFormatAndStorage", icon:"[SKIN]cube_blue.gif",
                     title:"Date and Time Format and Storage"},
                    {id:"77", ref:"group:keyboardEvents", icon:"[SKIN]cube_blue.gif",
                     title:"Keyboard Events"},
                    {id:"78", ref:"group:skinning", icon:"[SKIN]cube_blue.gif",
                     title:"Skinning / Theming"}
                ],
                id:"0"
            },
            {
                isOpen:"true",
                title:"Client Reference",
                children:[
                    {
                        isFolder:true,
                        title:"Grids",
                        id:"13",
                        children:[
                            {
                                id:"73",
                                ref:"class:ListGrid",
                                icon:"[SKIN]text_code_javascript.gif",
                                title:"ListGrid",
                                children:[
                                    {id:"74", ref:"group:editing", icon:"[SKIN]cube_blue.gif",
                                     title:"Grid Editing"},
                                    {id:"205", ref:"object:ListGridRecord",
                                     icon:"[SKIN]text_code_javascript.gif", title:"ListGridRecord"},
                                    {id:"206", ref:"object:groupNode",
                                     icon:"[SKIN]text_code_javascript.gif", title:"groupNode"},
                                    {id:"207", ref:"object:ListGridField",
                                     icon:"[SKIN]text_code_javascript.gif", title:"ListGridField"},
                                    {id:"208", ref:"object:HeaderSpan",
                                     icon:"[SKIN]text_code_javascript.gif", title:"HeaderSpan"},
                                    {id:"290", ref:"class:GroupingMessages",
                                     icon:"[SKIN]text_code_javascript.gif", title:"GroupingMessages"}
                                ]
                            },
                            {id:"193", ref:"class:DatabaseBrowser",
                             icon:"[SKIN]text_code_javascript.gif", title:"DatabaseBrowser"},
                            {id:"194", ref:"class:HibernateBrowser",
                             icon:"[SKIN]text_code_javascript.gif", title:"HibernateBrowser"},
                            {
                                id:"197",
                                ref:"class:TreeGrid",
                                icon:"[SKIN]text_code_javascript.gif",
                                title:"TreeGrid",
                                children:[
                                    {id:"198", ref:"object:TreeNode",
                                     icon:"[SKIN]text_code_javascript.gif", title:"TreeNode"},
                                    {id:"209", ref:"object:TreeGridField",
                                     icon:"[SKIN]text_code_javascript.gif", title:"TreeGridField"}
                                ]
                            },
                            {
                                id:"201",
                                ref:"class:DetailViewer",
                                icon:"[SKIN]text_code_javascript.gif",
                                title:"DetailViewer",
                                children:[
                                    {id:"202", ref:"object:DetailViewerRecord",
                                     icon:"[SKIN]text_code_javascript.gif", title:"DetailViewerRecord"},
                                    {id:"203", ref:"object:DetailViewerField",
                                     icon:"[SKIN]text_code_javascript.gif", title:"DetailViewerField"}
                                ]
                            },
                            {id:"214", ref:"class:TileLayout", icon:"[SKIN]text_code_javascript.gif",
                             title:"TileLayout"},
                            {id:"215", ref:"class:FlowLayout", icon:"[SKIN]text_code_javascript.gif",
                             title:"FlowLayout"},
                            {
                                id:"216",
                                ref:"class:TileGrid",
                                icon:"[SKIN]text_code_javascript.gif",
                                title:"TileGrid",
                                children:[
                                    {id:"218", ref:"class:SimpleTile",
                                     icon:"[SKIN]text_code_javascript.gif", title:"SimpleTile"}
                                ]
                            },
                            {id:"217", ref:"object:TileRecord", icon:"[SKIN]text_code_javascript.gif",
                             title:"TileRecord"},
                            {id:"219", ref:"class:ColumnTree", icon:"[SKIN]text_code_javascript.gif",
                             title:"ColumnTree"},
                            {id:"220", ref:"class:TableView", icon:"[SKIN]text_code_javascript.gif",
                             title:"TableView"},
                            {id:"221", ref:"class:DOMGrid", icon:"[SKIN]text_code_javascript.gif",
                             title:"DOMGrid"},
                            {id:"241", ref:"object:Hilite", icon:"[SKIN]text_code_javascript.gif",
                             title:"Hilite"}
                        ]
                    },
                    {
                        isFolder:true,
                        title:"Forms",
                        id:"14",
                        children:[
                            {id:"30", ref:"group:formLayout", icon:"[SKIN]cube_blue.gif",
                             title:"Form Layout"},
                            {id:"31", ref:"group:criteriaEditing", icon:"[SKIN]cube_blue.gif",
                             title:"Criteria Editing"},
                            {
                                id:"32",
                                title:"Form Items",
                                children:[
                                    {
                                        id:"33",
                                        ref:"class:FileItem",
                                        icon:"[SKIN]text_code_javascript.gif",
                                        title:"FileItem",
                                        children:[
                                            {id:"34", ref:"group:upload", icon:"[SKIN]cube_blue.gif",
                                             title:"Uploading Files"}
                                        ]
                                    },
                                    {id:"104", ref:"object:FormItemEventInfo",
                                     icon:"[SKIN]text_code_javascript.gif", title:"FormItemEventInfo"},
                                    {
                                        id:"105",
                                        ref:"class:FormItem",
                                        icon:"[SKIN]text_code_javascript.gif",
                                        title:"FormItem",
                                        children:[
                                            {id:"106", ref:"object:FormItemIcon",
                                             icon:"[SKIN]text_code_javascript.gif", title:"FormItemIcon"}
                                        ]
                                    },
                                    {id:"109", ref:"class:CanvasItem",
                                     icon:"[SKIN]text_code_javascript.gif", title:"CanvasItem"},
                                    {id:"110", ref:"class:TextItem",
                                     icon:"[SKIN]text_code_javascript.gif", title:"TextItem"},
                                    {id:"111", ref:"class:BlurbItem",
                                     icon:"[SKIN]text_code_javascript.gif", title:"BlurbItem"},
                                    {id:"112", ref:"class:ButtonItem",
                                     icon:"[SKIN]text_code_javascript.gif", title:"ButtonItem"},
                                    {id:"113", ref:"interface:PickList",
                                     icon:"[SKIN]text_code_javascript.gif", title:"PickList"},
                                    {id:"114", ref:"class:PickListMenu",
                                     icon:"[SKIN]text_code_javascript.gif", title:"PickListMenu"},
                                    {id:"115", ref:"class:SelectItem",
                                     icon:"[SKIN]text_code_javascript.gif", title:"SelectItem"},
                                    {id:"116", ref:"class:SelectOtherItem",
                                     icon:"[SKIN]text_code_javascript.gif", title:"SelectOtherItem"},
                                    {id:"117", ref:"class:CheckboxItem",
                                     icon:"[SKIN]text_code_javascript.gif", title:"CheckboxItem"},
                                    {id:"118", ref:"class:NativeCheckboxItem",
                                     icon:"[SKIN]text_code_javascript.gif", title:"NativeCheckboxItem"},
                                    {id:"119", ref:"class:HeaderItem",
                                     icon:"[SKIN]text_code_javascript.gif", title:"HeaderItem"},
                                    {id:"120", ref:"class:SectionItem",
                                     icon:"[SKIN]text_code_javascript.gif", title:"SectionItem"},
                                    {id:"121", ref:"class:HiddenItem",
                                     icon:"[SKIN]text_code_javascript.gif", title:"HiddenItem"},
                                    {id:"122", ref:"class:StaticTextItem",
                                     icon:"[SKIN]text_code_javascript.gif", title:"StaticTextItem"},
                                    {id:"123", ref:"class:LinkItem",
                                     icon:"[SKIN]text_code_javascript.gif", title:"LinkItem"},
                                    {id:"124", ref:"class:PasswordItem",
                                     icon:"[SKIN]text_code_javascript.gif", title:"PasswordItem"},
                                    {
                                        id:"125",
                                        ref:"class:RadioGroupItem",
                                        icon:"[SKIN]text_code_javascript.gif",
                                        title:"RadioGroupItem",
                                        children:[
                                            {id:"126", ref:"class:RadioItem",
                                             icon:"[SKIN]text_code_javascript.gif", title:"RadioItem"}
                                        ]
                                    },
                                    {id:"127", ref:"class:ResetItem",
                                     icon:"[SKIN]text_code_javascript.gif", title:"ResetItem"},
                                    {id:"128", ref:"class:DateItem",
                                     icon:"[SKIN]text_code_javascript.gif", title:"DateItem"},
                                    {id:"129", ref:"class:DateTimeItem",
                                     icon:"[SKIN]text_code_javascript.gif", title:"DateTimeItem"},
                                    {id:"130", ref:"class:SpacerItem",
                                     icon:"[SKIN]text_code_javascript.gif", title:"SpacerItem"},
                                    {id:"131", ref:"class:RowSpacerItem",
                                     icon:"[SKIN]text_code_javascript.gif", title:"RowSpacerItem"},
                                    {id:"132", ref:"class:SubmitItem",
                                     icon:"[SKIN]text_code_javascript.gif", title:"SubmitItem"},
                                    {id:"133", ref:"class:TextAreaItem",
                                     icon:"[SKIN]text_code_javascript.gif", title:"TextAreaItem"},
                                    {id:"134", ref:"class:AutoFitTextAreaItem",
                                     icon:"[SKIN]text_code_javascript.gif", title:"AutoFitTextAreaItem"},
                                    {id:"135", ref:"class:TimeItem",
                                     icon:"[SKIN]text_code_javascript.gif", title:"TimeItem"},
                                    {id:"136", ref:"class:ToolbarItem",
                                     icon:"[SKIN]text_code_javascript.gif", title:"ToolbarItem"},
                                    {id:"137", ref:"class:UploadItem",
                                     icon:"[SKIN]text_code_javascript.gif", title:"UploadItem"},
                                    {id:"138", ref:"class:ComboBoxItem",
                                     icon:"[SKIN]text_code_javascript.gif", title:"ComboBoxItem"},
                                    {
                                        id:"139",
                                        ref:"class:MultiFileItem",
                                        icon:"[SKIN]text_code_javascript.gif",
                                        title:"MultiFileItem",
                                        children:[
                                            {id:"140", ref:"class:MultiFilePicker",
                                             icon:"[SKIN]text_code_javascript.gif", title:"MultiFilePicker"}
                                        ]
                                    },
                                    {id:"141", ref:"class:SpinnerItem",
                                     icon:"[SKIN]text_code_javascript.gif", title:"SpinnerItem"},
                                    {id:"142", ref:"class:SliderItem",
                                     icon:"[SKIN]text_code_javascript.gif", title:"SliderItem"},
                                    {id:"143", ref:"class:ColorItem",
                                     icon:"[SKIN]text_code_javascript.gif", title:"ColorItem"},
                                    {id:"144", ref:"class:PickTreeItem",
                                     icon:"[SKIN]text_code_javascript.gif", title:"PickTreeItem"},
                                    {id:"145", ref:"class:IPickTreeItem",
                                     icon:"[SKIN]text_code_javascript.gif", title:"IPickTreeItem"},
                                    {id:"149", ref:"class:ViewFileItem",
                                     icon:"[SKIN]text_code_javascript.gif", title:"ViewFileItem"},
                                    {id:"150", ref:"class:DataPathItem",
                                     icon:"[SKIN]text_code_javascript.gif", title:"DataPathItem"},
                                    {id:"151", ref:"class:RelativeDateItem",
                                     icon:"[SKIN]text_code_javascript.gif", title:"RelativeDateItem"},
                                    {id:"152", ref:"class:DateRangeItem",
                                     icon:"[SKIN]text_code_javascript.gif", title:"DateRangeItem"},
                                    {id:"153", ref:"object:DateRange",
                                     icon:"[SKIN]text_code_javascript.gif", title:"DateRange"},
                                    {id:"154", ref:"class:DateRangeDialog",
                                     icon:"[SKIN]text_code_javascript.gif", title:"DateRangeDialog"},
                                    {id:"155", ref:"class:MiniDateRangeItem",
                                     icon:"[SKIN]text_code_javascript.gif", title:"MiniDateRangeItem"},
                                    {id:"299", ref:"class:RichTextItem",
                                     icon:"[SKIN]text_code_javascript.gif", title:"RichTextItem"}
                                ]
                            },
                            {id:"101", ref:"class:DateChooser", icon:"[SKIN]text_code_javascript.gif",
                             title:"DateChooser"},
                            {id:"103", ref:"class:DynamicForm", icon:"[SKIN]text_code_javascript.gif",
                             title:"DynamicForm"},
                            {
                                id:"107",
                                ref:"class:Validator",
                                icon:"[SKIN]text_code_javascript.gif",
                                title:"Validator",
                                children:[
                                    {id:"108", ref:"object:validatorDefinition",
                                     icon:"[SKIN]text_code_javascript.gif", title:"validatorDefinition"}
                                ]
                            },
                            {id:"146", ref:"class:SearchForm", icon:"[SKIN]text_code_javascript.gif",
                             title:"SearchForm"},
                            {id:"147", ref:"class:ValuesManager",
                             icon:"[SKIN]text_code_javascript.gif", title:"ValuesManager"},
                            {id:"148", ref:"class:ColorPicker", icon:"[SKIN]text_code_javascript.gif",
                             title:"ColorPicker"},
                            {id:"181", ref:"class:PropertySheet",
                             icon:"[SKIN]text_code_javascript.gif", title:"PropertySheet"},
                            {id:"188", ref:"class:FilterClause", icon:"[SKIN]text_code_javascript.gif",
                             title:"FilterClause"},
                            {id:"189", ref:"class:FilterBuilder",
                             icon:"[SKIN]text_code_javascript.gif", title:"FilterBuilder"}
                        ]
                    },
                    {
                        isFolder:true,
                        title:"Layout",
                        id:"15",
                        children:[
                            {
                                id:"249",
                                ref:"class:TabSet",
                                icon:"[SKIN]text_code_javascript.gif",
                                title:"TabSet",
                                children:[
                                    {id:"250", ref:"class:TabBar",
                                     icon:"[SKIN]text_code_javascript.gif", title:"TabBar"},
                                    {id:"258", ref:"object:Tab", icon:"[SKIN]text_code_javascript.gif",
                                     title:"Tab"}
                                ]
                            },
                            {id:"251", ref:"class:Window", icon:"[SKIN]text_code_javascript.gif",
                             title:"Window"},
                            {
                                id:"252",
                                ref:"class:PortalLayout",
                                icon:"[SKIN]text_code_javascript.gif",
                                title:"PortalLayout",
                                children:[
                                    {id:"253", ref:"class:Portlet",
                                     icon:"[SKIN]text_code_javascript.gif", title:"Portlet"}
                                ]
                            },
                            {id:"261", ref:"class:Layout", icon:"[SKIN]text_code_javascript.gif",
                             title:"Layout"},
                            {id:"262", ref:"class:HLayout", icon:"[SKIN]text_code_javascript.gif",
                             title:"HLayout"},
                            {id:"263", ref:"class:VLayout", icon:"[SKIN]text_code_javascript.gif",
                             title:"VLayout"},
                            {id:"264", ref:"class:HStack", icon:"[SKIN]text_code_javascript.gif",
                             title:"HStack"},
                            {id:"265", ref:"class:VStack", icon:"[SKIN]text_code_javascript.gif",
                             title:"VStack"},
                            {id:"266", ref:"class:LayoutSpacer", icon:"[SKIN]text_code_javascript.gif",
                             title:"LayoutSpacer"},
                            {id:"274", ref:"class:Toolbar", icon:"[SKIN]text_code_javascript.gif",
                             title:"Toolbar"},
                            {
                                id:"277",
                                ref:"class:ToolStrip",
                                icon:"[SKIN]text_code_javascript.gif",
                                title:"ToolStrip",
                                children:[
                                    {id:"278", ref:"class:ToolStripSeparator",
                                     icon:"[SKIN]text_code_javascript.gif", title:"ToolStripSeparator"},
                                    {id:"289", ref:"class:ToolStripResizer",
                                     icon:"[SKIN]text_code_javascript.gif", title:"ToolStripResizer"}
                                ]
                            },
                            {
                                id:"279",
                                ref:"class:SectionStack",
                                icon:"[SKIN]text_code_javascript.gif",
                                title:"SectionStack",
                                children:[
                                    {id:"280", ref:"object:SectionStackSection",
                                     icon:"[SKIN]text_code_javascript.gif", title:"SectionStackSection"},
                                    {id:"281", ref:"class:SectionHeader",
                                     icon:"[SKIN]text_code_javascript.gif", title:"SectionHeader"},
                                    {id:"282", ref:"class:ImgSectionHeader",
                                     icon:"[SKIN]text_code_javascript.gif", title:"ImgSectionHeader"}
                                ]
                            },
                            {id:"286", ref:"class:Splitbar", icon:"[SKIN]text_code_javascript.gif",
                             title:"Splitbar"},
                            {id:"287", ref:"class:ImgSplitbar", icon:"[SKIN]text_code_javascript.gif",
                             title:"ImgSplitbar"},
                            {id:"288", ref:"class:Snapbar", icon:"[SKIN]text_code_javascript.gif",
                             title:"Snapbar"},
                            {
                                id:"292",
                                ref:"class:NavigationBar",
                                icon:"[SKIN]text_code_javascript.gif",
                                title:"NavigationBar",
                                children:[
                                    {id:"293", ref:"class:NavigationButton",
                                     icon:"[SKIN]text_code_javascript.gif", title:"NavigationButton"}
                                ]
                            },
                            {id:"294", ref:"class:SplitPane", icon:"[SKIN]text_code_javascript.gif",
                             title:"SplitPane"}
                        ]
                    },
                    {
                        isFolder:true,
                        title:"Control",
                        id:"16",
                        children:[
                            {id:"80", ref:"group:Prompting", icon:"[SKIN]cube_blue.gif",
                             title:"Prompting"},
                            {id:"102", ref:"class:Slider", icon:"[SKIN]text_code_javascript.gif",
                             title:"Slider"},
                            {
                                id:"210",
                                ref:"class:Menu",
                                icon:"[SKIN]text_code_javascript.gif",
                                title:"Menu",
                                children:[
                                    {id:"211", ref:"object:MenuItem",
                                     icon:"[SKIN]text_code_javascript.gif", title:"MenuItem"}
                                ]
                            },
                            {id:"212", ref:"class:MenuButton", icon:"[SKIN]text_code_javascript.gif",
                             title:"MenuButton"},
                            {id:"213", ref:"class:IMenuButton", icon:"[SKIN]text_code_javascript.gif",
                             title:"IMenuButton"},
                            {id:"222", ref:"class:MenuBar", icon:"[SKIN]text_code_javascript.gif",
                             title:"MenuBar"},
                            {id:"245", ref:"class:Hover", icon:"[SKIN]text_code_javascript.gif",
                             title:"Hover"},
                            {id:"254", ref:"class:Dialog", icon:"[SKIN]text_code_javascript.gif",
                             title:"Dialog"},
                            {id:"255", ref:"class:LoginDialog", icon:"[SKIN]text_code_javascript.gif",
                             title:"LoginDialog"},
                            {
                                id:"267",
                                ref:"class:Button",
                                icon:"[SKIN]text_code_javascript.gif",
                                title:"Button",
                                children:[
                                    {id:"268", ref:"class:AutoFitButton",
                                     icon:"[SKIN]text_code_javascript.gif", title:"AutoFitButton"}
                                ]
                            },
                            {id:"269", ref:"class:IButton", icon:"[SKIN]text_code_javascript.gif",
                             title:"IButton"},
                            {id:"273", ref:"class:Progressbar", icon:"[SKIN]text_code_javascript.gif",
                             title:"Progressbar"},
                            {id:"275", ref:"class:ImgButton", icon:"[SKIN]text_code_javascript.gif",
                             title:"ImgButton"},
                            {id:"276", ref:"class:StretchImgButton",
                             icon:"[SKIN]text_code_javascript.gif", title:"StretchImgButton"}
                        ]
                    },
                    {
                        isFolder:true,
                        title:"Foundation",
                        id:"17",
                        children:[
                            {id:"99", ref:"object:Browser", icon:"[SKIN]text_code_javascript.gif",
                             title:"Browser"},
                            {id:"182", ref:"class:ViewLoader", icon:"[SKIN]text_code_javascript.gif",
                             title:"ViewLoader"},
                            {id:"183", ref:"class:HTMLFlow", icon:"[SKIN]text_code_javascript.gif",
                             title:"HTMLFlow"},
                            {id:"184", ref:"class:HTMLPane", icon:"[SKIN]text_code_javascript.gif",
                             title:"HTMLPane"},
                            {id:"204", ref:"class:GridRenderer", icon:"[SKIN]text_code_javascript.gif",
                             title:"GridRenderer"},
                            {
                                id:"238",
                                ref:"class:Canvas",
                                icon:"[SKIN]text_code_javascript.gif",
                                title:"Canvas",
                                children:[
                                    {id:"239", ref:"object:ImgProperties",
                                     icon:"[SKIN]text_code_javascript.gif", title:"ImgProperties"}
                                ]
                            },
                            {id:"244", ref:"class:EdgedCanvas", icon:"[SKIN]text_code_javascript.gif",
                             title:"EdgedCanvas"},
                            {id:"248", ref:"class:ImgTab", icon:"[SKIN]text_code_javascript.gif",
                             title:"ImgTab"},
                            {id:"260", ref:"class:StatefulCanvas",
                             icon:"[SKIN]text_code_javascript.gif", title:"StatefulCanvas"},
                            {id:"270", ref:"class:Img", icon:"[SKIN]text_code_javascript.gif",
                             title:"Img"},
                            {id:"271", ref:"class:StretchImg", icon:"[SKIN]text_code_javascript.gif",
                             title:"StretchImg"},
                            {id:"272", ref:"class:Label", icon:"[SKIN]text_code_javascript.gif",
                             title:"Label"},
                            {id:"283", ref:"class:Scrollbar", icon:"[SKIN]text_code_javascript.gif",
                             title:"Scrollbar"},
                            {
                                id:"284",
                                title:"ScrollBar",
                                children:[
                                    {id:"285", ref:"class:ScrollThumb",
                                     icon:"[SKIN]text_code_javascript.gif", title:"ScrollThumb"}
                                ]
                            },
                            {id:"298", ref:"class:RichTextEditor",
                             icon:"[SKIN]text_code_javascript.gif", title:"RichTextEditor"}
                        ]
                    },
                    {
                        isFolder:true,
                        title:"Data Binding",
                        id:"18",
                        children:[
                            {
                                id:"36",
                                ref:"class:DataSource",
                                icon:"[SKIN]text_code_javascript.gif",
                                title:"DataSource",
                                children:[
                                    {id:"37", ref:"group:dataSourceDeclaration",
                                     icon:"[SKIN]cube_blue.gif", title:"Creating DataSources"},
                                    {id:"44", ref:"group:sqlDataSource", icon:"[SKIN]cube_blue.gif",
                                     title:"SQL DataSources"},
                                    {id:"45", ref:"group:adminConsole", icon:"[SKIN]cube_blue.gif",
                                     title:"Admin Console"},
                                    {id:"46", ref:"group:sqlSettings", icon:"[SKIN]cube_blue.gif",
                                     title:"SQL Database Settings in <code>server.properties</code>"},
                                    {id:"47", ref:"group:clientOnlyDataSources",
                                     icon:"[SKIN]cube_blue.gif", title:"Client Only DataSources"},
                                    {id:"48", ref:"group:serverDataSourceImplementation",
                                     icon:"[SKIN]cube_blue.gif", title:"Notes on Server-side DataSource Implementations"},
                                    {id:"157", ref:"object:Record",
                                     icon:"[SKIN]text_code_javascript.gif", title:"Record"},
                                    {id:"158", ref:"class:DataSourceField",
                                     icon:"[SKIN]text_code_javascript.gif", title:"DataSourceField"},
                                    {id:"159", ref:"object:SerializationContext",
                                     icon:"[SKIN]text_code_javascript.gif", title:"SerializationContext"},
                                    {id:"163", ref:"class:OperationBinding",
                                     icon:"[SKIN]text_code_javascript.gif", title:"OperationBinding"},
                                    {id:"164", ref:"object:DSRequestModifier",
                                     icon:"[SKIN]text_code_javascript.gif", title:"DSRequestModifier"},
                                    {id:"165", ref:"class:Mail", icon:"[SKIN]text_code_javascript.gif",
                                     title:"Mail"},
                                    {id:"166", ref:"object:AdvancedCriteria",
                                     icon:"[SKIN]text_code_javascript.gif", title:"AdvancedCriteria"},
                                    {id:"167", ref:"object:Criterion",
                                     icon:"[SKIN]text_code_javascript.gif", title:"Criterion"},
                                    {id:"168", ref:"object:Operator",
                                     icon:"[SKIN]text_code_javascript.gif", title:"Operator"},
                                    {id:"187", ref:"class:Operators",
                                     icon:"[SKIN]text_code_javascript.gif", title:"Operators"},
                                    {id:"329", ref:"type:DSCallback", icon:"[SKIN]text_code.gif",
                                     title:"DSCallback"},
                                    {id:"336", ref:"type:VelocityExpression",
                                     icon:"[SKIN]text_code.gif", title:"VelocityExpression"},
                                    {id:"337", ref:"type:OperatorValueType",
                                     icon:"[SKIN]text_code.gif", title:"OperatorValueType"},
                                    {id:"338", ref:"type:OperatorId", icon:"[SKIN]text_code.gif",
                                     title:"OperatorId"}
                                ]
                            },
                            {id:"50", ref:"group:clientDataIntegration", icon:"[SKIN]cube_blue.gif",
                             title:"Client-side Data Integration"},
                            {id:"59", ref:"group:wsdlBinding", icon:"[SKIN]cube_blue.gif",
                             title:"WSDL Binding"},
                            {id:"62", ref:"group:operations", icon:"[SKIN]cube_blue.gif",
                             title:"Operations Overview"},
                            {id:"63", ref:"group:dataSourceOperations", icon:"[SKIN]cube_blue.gif",
                             title:"DataSource Operations"},
                            {id:"68", ref:"group:metadataImport", icon:"[SKIN]cube_blue.gif",
                             title:"Metadata Import"},
                            {id:"72", ref:"group:treeDataBinding", icon:"[SKIN]cube_blue.gif",
                             title:"Tree DataBinding"},
                            {id:"79", ref:"group:dataBoundComponentMethods",
                             icon:"[SKIN]cube_blue.gif", title:"DataBound Component Methods"},
                            {id:"156", ref:"class:XMLTools", icon:"[SKIN]text_code_javascript.gif",
                             title:"XMLTools"},
                            {id:"160", ref:"class:DSResponse", icon:"[SKIN]text_code_javascript.gif",
                             title:"DSResponse"},
                            {id:"161", ref:"class:DSRequest", icon:"[SKIN]text_code_javascript.gif",
                             title:"DSRequest"},
                            {id:"169", ref:"class:XJSONDataSource",
                             icon:"[SKIN]text_code_javascript.gif", title:"XJSONDataSource"},
                            {id:"170", ref:"class:WebService", icon:"[SKIN]text_code_javascript.gif",
                             title:"WebService"},
                            {id:"171", ref:"class:SchemaSet", icon:"[SKIN]text_code_javascript.gif",
                             title:"SchemaSet"},
                            {id:"172", ref:"class:WSRequest", icon:"[SKIN]text_code_javascript.gif",
                             title:"WSRequest"},
                            {id:"177", ref:"class:ResultSet", icon:"[SKIN]text_code_javascript.gif",
                             title:"ResultSet"},
                            {id:"178", ref:"class:ResultTree", icon:"[SKIN]text_code_javascript.gif",
                             title:"ResultTree"},
                            {id:"179", ref:"class:DataView", icon:"[SKIN]text_code_javascript.gif",
                             title:"DataView"},
                            {id:"180", ref:"class:Offline", icon:"[SKIN]text_code_javascript.gif",
                             title:"Offline"},
                            {id:"185", ref:"class:WSDataSource", icon:"[SKIN]text_code_javascript.gif",
                             title:"WSDataSource"},
                            {id:"186", ref:"class:RestDataSource",
                             icon:"[SKIN]text_code_javascript.gif", title:"RestDataSource"},
                            {
                                id:"224",
                                ref:"class:FormulaBuilder",
                                icon:"[SKIN]text_code_javascript.gif",
                                title:"FormulaBuilder",
                                children:[
                                    {id:"242", ref:"class:MathFunction",
                                     icon:"[SKIN]text_code_javascript.gif", title:"MathFunction"},
                                    {id:"243", ref:"object:TestFunctionResult",
                                     icon:"[SKIN]text_code_javascript.gif", title:"TestFunctionResult"}
                                ]
                            },
                            {id:"225", ref:"class:SummaryBuilder",
                             icon:"[SKIN]text_code_javascript.gif", title:"SummaryBuilder"},
                            {id:"240", ref:"interface:DataBoundComponent",
                             icon:"[SKIN]text_code_javascript.gif", title:"DataBoundComponent"},
                            {id:"246", ref:"class:JSON", icon:"[SKIN]text_code_javascript.gif",
                             title:"JSON"},
                            {id:"247", ref:"class:JSONEncoder", icon:"[SKIN]text_code_javascript.gif",
                             title:"JSONEncoder"},
                            {id:"256", ref:"class:MultiSortPanel",
                             icon:"[SKIN]text_code_javascript.gif", title:"MultiSortPanel"},
                            {id:"257", ref:"class:MultiSortDialog",
                             icon:"[SKIN]text_code_javascript.gif", title:"MultiSortDialog"},
                            {id:"291", ref:"class:SimpleType", icon:"[SKIN]text_code_javascript.gif",
                             title:"SimpleType"},
                            {id:"344", ref:"type:Criteria", icon:"[SKIN]text_code.gif",
                             title:"Criteria"}
                        ]
                    },
                    {
                        isFolder:true,
                        title:"RPC",
                        id:"19",
                        children:[
                            {id:"61", ref:"group:relogin", icon:"[SKIN]cube_blue.gif", title:"Relogin"},
                            {id:"69", ref:"group:dmiOverview", icon:"[SKIN]cube_blue.gif",
                             title:"Direct Method Invocation"},
                            {id:"70", ref:"group:applicationDeclaration", icon:"[SKIN]cube_blue.gif",
                             title:"Application Declaration Files"},
                            {id:"162", ref:"class:ServerObject", icon:"[SKIN]text_code_javascript.gif",
                             title:"ServerObject"},
                            {id:"173", ref:"class:RPCManager", icon:"[SKIN]text_code_javascript.gif",
                             title:"RPCManager"},
                            {id:"174", ref:"class:RPCRequest", icon:"[SKIN]text_code_javascript.gif",
                             title:"RPCRequest"},
                            {id:"175", ref:"class:RPCResponse", icon:"[SKIN]text_code_javascript.gif",
                             title:"RPCResponse"},
                            {id:"176", ref:"class:DMI", icon:"[SKIN]text_code_javascript.gif",
                             title:"DMI"},
                            {id:"341", ref:"type:RPCCallback", icon:"[SKIN]text_code.gif",
                             title:"RPCCallback"}
                        ]
                    },
                    {
                        isFolder:true,
                        title:"System",
                        id:"20",
                        children:[
                            {id:"60", ref:"group:platformDependencies", icon:"[SKIN]cube_blue.gif",
                             title:"Platform Dependencies"},
                            {id:"75", ref:"group:stringMethods", icon:"[SKIN]cube_blue.gif",
                             title:"String Methods Overview"},
                            {id:"98", ref:"class:isc", icon:"[SKIN]text_code_javascript.gif",
                             title:"isc"},
                            {id:"100", ref:"class:History", icon:"[SKIN]text_code_javascript.gif",
                             title:"History"},
                            {id:"195", ref:"interface:List", icon:"[SKIN]text_code_javascript.gif",
                             title:"List"},
                            {
                                id:"196",
                                ref:"class:Tree",
                                icon:"[SKIN]text_code_javascript.gif",
                                title:"Tree",
                                children:[
                                    {id:"199", ref:"object:TreeNode",
                                     icon:"[SKIN]text_code_javascript.gif", title:"TreeNode"}
                                ]
                            },
                            {
                                id:"200",
                                ref:"class:Selection",
                                icon:"[SKIN]text_code_javascript.gif",
                                title:"Selection",
                                children:[
                                    {id:"223", ref:"class:CellSelection",
                                     icon:"[SKIN]text_code_javascript.gif", title:"CellSelection"}
                                ]
                            },
                            {id:"226", ref:"object:isA", icon:"[SKIN]text_code_javascript.gif",
                             title:"isA"},
                            {id:"227", ref:"object:ClassFactory",
                             icon:"[SKIN]text_code_javascript.gif", title:"ClassFactory"},
                            {id:"228", ref:"class:Class", icon:"[SKIN]text_code_javascript.gif",
                             title:"Class"},
                            {id:"229", ref:"object:Array", icon:"[SKIN]text_code_javascript.gif",
                             title:"Array"},
                            {id:"230", ref:"object:Number", icon:"[SKIN]text_code_javascript.gif",
                             title:"Number"},
                            {id:"231", ref:"class:Date", icon:"[SKIN]text_code_javascript.gif",
                             title:"Date"},
                            {id:"232", ref:"class:String", icon:"[SKIN]text_code_javascript.gif",
                             title:"String"},
                            {id:"233", ref:"class:Log", icon:"[SKIN]text_code_javascript.gif",
                             title:"Log"},
                            {id:"234", ref:"class:Time", icon:"[SKIN]text_code_javascript.gif",
                             title:"Time"},
                            {id:"235", ref:"class:Page", icon:"[SKIN]text_code_javascript.gif",
                             title:"Page"},
                            {id:"236", ref:"class:Timer", icon:"[SKIN]text_code_javascript.gif",
                             title:"Timer"},
                            {id:"237", ref:"class:EventHandler", icon:"[SKIN]text_code_javascript.gif",
                             title:"EventHandler"},
                            {id:"259", ref:"object:animationShowEffect",
                             icon:"[SKIN]text_code_javascript.gif", title:"animationShowEffect"},
                            {
                                id:"300",
                                title:"Types",
                                children:[
                                    {id:"301", ref:"type:AutoSelectionModel",
                                     icon:"[SKIN]text_code.gif", title:"AutoSelectionModel"},
                                    {id:"302", ref:"type:SelectionBoundary",
                                     icon:"[SKIN]text_code.gif", title:"SelectionBoundary"},
                                    {id:"303", ref:"type:Axis", icon:"[SKIN]text_code.gif",
                                     title:"Axis"},
                                    {id:"304", ref:"type:ChartType", icon:"[SKIN]text_code.gif",
                                     title:"ChartType"},
                                    {id:"305", ref:"type:FormMethod", icon:"[SKIN]text_code.gif",
                                     title:"FormMethod"},
                                    {id:"306", ref:"type:Encoding", icon:"[SKIN]text_code.gif",
                                     title:"Encoding"},
                                    {id:"307", ref:"type:TitleOrientation", icon:"[SKIN]text_code.gif",
                                     title:"TitleOrientation"},
                                    {id:"308", ref:"type:FormItemType", icon:"[SKIN]text_code.gif",
                                     title:"FormItemType"},
                                    {id:"309", ref:"type:FormItemBaseStyle",
                                     icon:"[SKIN]text_code.gif", title:"FormItemBaseStyle"},
                                    {id:"310", ref:"type:ValidatorType", icon:"[SKIN]text_code.gif",
                                     title:"ValidatorType"},
                                    {id:"311", ref:"type:FieldAppearance", icon:"[SKIN]text_code.gif",
                                     title:"FieldAppearance"},
                                    {id:"312", ref:"type:CharacterCasing", icon:"[SKIN]text_code.gif",
                                     title:"CharacterCasing"},
                                    {id:"313", ref:"type:MultipleAppearance",
                                     icon:"[SKIN]text_code.gif", title:"MultipleAppearance"},
                                    {id:"314", ref:"type:DateItemSelectorFormat",
                                     icon:"[SKIN]text_code.gif", title:"DateItemSelectorFormat"},
                                    {id:"315", ref:"type:TEXTAREA_WRAP", icon:"[SKIN]text_code.gif",
                                     title:"TEXTAREA_WRAP"},
                                    {id:"316", ref:"type:PanelHeaderPlacement",
                                     icon:"[SKIN]text_code.gif", title:"PanelHeaderPlacement"},
                                    {id:"317", ref:"type:RelativeDate", icon:"[SKIN]text_code.gif",
                                     title:"RelativeDate"},
                                    {id:"318", ref:"type:RelativeDateString",
                                     icon:"[SKIN]text_code.gif", title:"RelativeDateString"},
                                    {id:"319", ref:"type:TimeUnit", icon:"[SKIN]text_code.gif",
                                     title:"TimeUnit"},
                                    {id:"320", ref:"type:XMLDocument", icon:"[SKIN]text_code.gif",
                                     title:"XMLDocument"},
                                    {id:"321", ref:"type:XMLElement", icon:"[SKIN]text_code.gif",
                                     title:"XMLElement"},
                                    {id:"322", ref:"type:DSOperationType", icon:"[SKIN]text_code.gif",
                                     title:"DSOperationType"},
                                    {id:"323", ref:"type:DSDataFormat", icon:"[SKIN]text_code.gif",
                                     title:"DSDataFormat"},
                                    {id:"324", ref:"type:DSServerType", icon:"[SKIN]text_code.gif",
                                     title:"DSServerType"},
                                    {id:"325", ref:"type:EnumTranslateStrategy",
                                     icon:"[SKIN]text_code.gif", title:"EnumTranslateStrategy"},
                                    {id:"326", ref:"type:ValueMap", icon:"[SKIN]text_code.gif",
                                     title:"ValueMap"},
                                    {id:"327", ref:"type:HashAlgorithm", icon:"[SKIN]text_code.gif",
                                     title:"HashAlgorithm"},
                                    {id:"328", ref:"type:FieldType", icon:"[SKIN]text_code.gif",
                                     title:"FieldType"},
                                    {id:"330", ref:"type:TextMatchStyle", icon:"[SKIN]text_code.gif",
                                     title:"TextMatchStyle"},
                                    {id:"331", ref:"type:ExportFormat", icon:"[SKIN]text_code.gif",
                                     title:"ExportFormat"},
                                    {id:"332", ref:"type:ExportDisplay", icon:"[SKIN]text_code.gif",
                                     title:"ExportDisplay"},
                                    {id:"333", ref:"type:LineBreakStyle", icon:"[SKIN]text_code.gif",
                                     title:"LineBreakStyle"},
                                    {id:"334", ref:"type:ValidationMode", icon:"[SKIN]text_code.gif",
                                     title:"ValidationMode"},
                                    {id:"335", ref:"type:DSProtocol", icon:"[SKIN]text_code.gif",
                                     title:"DSProtocol"},
                                    {id:"339", ref:"type:CriteriaCombineOperator",
                                     icon:"[SKIN]text_code.gif", title:"CriteriaCombineOperator"},
                                    {id:"340", ref:"type:RecordSummaryFunction",
                                     icon:"[SKIN]text_code.gif", title:"RecordSummaryFunction"},
                                    {id:"342", ref:"type:RPCTransport", icon:"[SKIN]text_code.gif",
                                     title:"RPCTransport"},
                                    {id:"343", ref:"type:PromptStyle", icon:"[SKIN]text_code.gif",
                                     title:"PromptStyle"},
                                    {id:"345", ref:"type:FetchMode", icon:"[SKIN]text_code.gif",
                                     title:"FetchMode"},
                                    {id:"346", ref:"type:CriteriaPolicy", icon:"[SKIN]text_code.gif",
                                     title:"CriteriaPolicy"},
                                    {id:"347", ref:"type:LogicalOperator", icon:"[SKIN]text_code.gif",
                                     title:"LogicalOperator"},
                                    {id:"348", ref:"type:TopOperatorAppearance",
                                     icon:"[SKIN]text_code.gif", title:"TopOperatorAppearance"},
                                    {id:"349", ref:"type:ViewName", icon:"[SKIN]text_code.gif",
                                     title:"ViewName"},
                                    {id:"350", ref:"type:DisplayNodeType", icon:"[SKIN]text_code.gif",
                                     title:"DisplayNodeType"},
                                    {id:"351", ref:"type:LoadState", icon:"[SKIN]text_code.gif",
                                     title:"LoadState"},
                                    {id:"352", ref:"type:TreeModelType", icon:"[SKIN]text_code.gif",
                                     title:"TreeModelType"},
                                    {id:"353", ref:"type:SelectionStyle", icon:"[SKIN]text_code.gif",
                                     title:"SelectionStyle"},
                                    {id:"354", ref:"type:SortArrow", icon:"[SKIN]text_code.gif",
                                     title:"SortArrow"},
                                    {id:"355", ref:"type:ReorderPosition", icon:"[SKIN]text_code.gif",
                                     title:"ReorderPosition"},
                                    {id:"356", ref:"type:RowEndEditAction", icon:"[SKIN]text_code.gif",
                                     title:"RowEndEditAction"},
                                    {id:"357", ref:"type:EnterKeyEditAction",
                                     icon:"[SKIN]text_code.gif", title:"EnterKeyEditAction"},
                                    {id:"358", ref:"type:EscapeKeyEditAction",
                                     icon:"[SKIN]text_code.gif", title:"EscapeKeyEditAction"},
                                    {id:"359", ref:"type:EditCompletionEvent",
                                     icon:"[SKIN]text_code.gif", title:"EditCompletionEvent"},
                                    {id:"360", ref:"type:GroupStartOpen", icon:"[SKIN]text_code.gif",
                                     title:"GroupStartOpen"},
                                    {id:"361", ref:"type:ListGridFieldType",
                                     icon:"[SKIN]text_code.gif", title:"ListGridFieldType"},
                                    {id:"362", ref:"type:AutoFitEvent", icon:"[SKIN]text_code.gif",
                                     title:"AutoFitEvent"},
                                    {id:"363", ref:"type:AutoFitWidthApproach",
                                     icon:"[SKIN]text_code.gif", title:"AutoFitWidthApproach"},
                                    {id:"364", ref:"type:AutoFitIconFieldType",
                                     icon:"[SKIN]text_code.gif", title:"AutoFitIconFieldType"},
                                    {id:"365", ref:"type:EmbeddedPosition", icon:"[SKIN]text_code.gif",
                                     title:"EmbeddedPosition"},
                                    {id:"366", ref:"type:RecordComponentPoolingMode",
                                     icon:"[SKIN]text_code.gif", title:"RecordComponentPoolingMode"},
                                    {id:"367", ref:"type:ListGridEditEvent",
                                     icon:"[SKIN]text_code.gif", title:"ListGridEditEvent"},
                                    {id:"368", ref:"type:DragTrackerMode", icon:"[SKIN]text_code.gif",
                                     title:"DragTrackerMode"},
                                    {id:"369", ref:"type:ExpansionMode", icon:"[SKIN]text_code.gif",
                                     title:"ExpansionMode"},
                                    {id:"370", ref:"type:listGridFieldState",
                                     icon:"[SKIN]text_code.gif", title:"listGridFieldState"},
                                    {id:"371", ref:"type:SelectionAppearance",
                                     icon:"[SKIN]text_code.gif", title:"SelectionAppearance"},
                                    {id:"372", ref:"type:listGridSelectedState",
                                     icon:"[SKIN]text_code.gif", title:"listGridSelectedState"},
                                    {id:"373", ref:"type:listGridSortState",
                                     icon:"[SKIN]text_code.gif", title:"listGridSortState"},
                                    {id:"374", ref:"type:listGridViewState",
                                     icon:"[SKIN]text_code.gif", title:"listGridViewState"},
                                    {id:"375", ref:"type:HoverMode", icon:"[SKIN]text_code.gif",
                                     title:"HoverMode"},
                                    {id:"376", ref:"type:treeGridOpenState",
                                     icon:"[SKIN]text_code.gif", title:"treeGridOpenState"},
                                    {id:"377", ref:"type:treeGridViewState",
                                     icon:"[SKIN]text_code.gif", title:"treeGridViewState"},
                                    {id:"378", ref:"type:MenuFieldID", icon:"[SKIN]text_code.gif",
                                     title:"MenuFieldID"},
                                    {id:"379", ref:"type:TileLayoutPolicy", icon:"[SKIN]text_code.gif",
                                     title:"TileLayoutPolicy"},
                                    {id:"380", ref:"type:TableMode", icon:"[SKIN]text_code.gif",
                                     title:"TableMode"},
                                    {id:"381", ref:"type:RecordLayout", icon:"[SKIN]text_code.gif",
                                     title:"RecordLayout"},
                                    {id:"382", ref:"type:NavigationMode", icon:"[SKIN]text_code.gif",
                                     title:"NavigationMode"},
                                    {id:"383", ref:"type:Object", icon:"[SKIN]text_code.gif",
                                     title:"Object"},
                                    {id:"384", ref:"type:SCClassName", icon:"[SKIN]text_code.gif",
                                     title:"SCClassName"},
                                    {id:"385", ref:"type:Callback", icon:"[SKIN]text_code.gif",
                                     title:"Callback"},
                                    {id:"386", ref:"type:Properties", icon:"[SKIN]text_code.gif",
                                     title:"Properties"},
                                    {id:"387", ref:"type:ObjectLiteral", icon:"[SKIN]text_code.gif",
                                     title:"ObjectLiteral"},
                                    {id:"388", ref:"type:AutoChild", icon:"[SKIN]text_code.gif",
                                     title:"AutoChild"},
                                    {id:"389", ref:"type:DateInputFormat", icon:"[SKIN]text_code.gif",
                                     title:"DateInputFormat"},
                                    {id:"390", ref:"type:DateDisplayFormat",
                                     icon:"[SKIN]text_code.gif", title:"DateDisplayFormat"},
                                    {id:"391", ref:"type:LogPriority", icon:"[SKIN]text_code.gif",
                                     title:"LogPriority"},
                                    {id:"392", ref:"type:SortDirection", icon:"[SKIN]text_code.gif",
                                     title:"SortDirection"},
                                    {id:"393", ref:"type:timeFormatter", icon:"[SKIN]text_code.gif",
                                     title:"timeFormatter"},
                                    {id:"394", ref:"type:PageOrientation", icon:"[SKIN]text_code.gif",
                                     title:"PageOrientation"},
                                    {id:"395", ref:"type:SendMethod", icon:"[SKIN]text_code.gif",
                                     title:"SendMethod"},
                                    {id:"396", ref:"type:FireStyle", icon:"[SKIN]text_code.gif",
                                     title:"FireStyle"},
                                    {id:"397", ref:"type:PageEvent", icon:"[SKIN]text_code.gif",
                                     title:"PageEvent"},
                                    {id:"398", ref:"type:DragAppearance", icon:"[SKIN]text_code.gif",
                                     title:"DragAppearance"},
                                    {id:"399", ref:"type:DragIntersectStyle",
                                     icon:"[SKIN]text_code.gif", title:"DragIntersectStyle"},
                                    {id:"400", ref:"type:KeyName", icon:"[SKIN]text_code.gif",
                                     title:"KeyName"},
                                    {id:"401", ref:"type:KeyIdentifier", icon:"[SKIN]text_code.gif",
                                     title:"KeyIdentifier"},
                                    {id:"402", ref:"type:ClickMaskMode", icon:"[SKIN]text_code.gif",
                                     title:"ClickMaskMode"},
                                    {id:"403", ref:"type:Positioning", icon:"[SKIN]text_code.gif",
                                     title:"Positioning"},
                                    {id:"404", ref:"type:Visibility", icon:"[SKIN]text_code.gif",
                                     title:"Visibility"},
                                    {id:"405", ref:"type:Overflow", icon:"[SKIN]text_code.gif",
                                     title:"Overflow"},
                                    {id:"406", ref:"type:Alignment", icon:"[SKIN]text_code.gif",
                                     title:"Alignment"},
                                    {id:"407", ref:"type:VerticalAlignment",
                                     icon:"[SKIN]text_code.gif", title:"VerticalAlignment"},
                                    {id:"408", ref:"type:Side", icon:"[SKIN]text_code.gif",
                                     title:"Side"},
                                    {id:"409", ref:"type:Direction", icon:"[SKIN]text_code.gif",
                                     title:"Direction"},
                                    {id:"410", ref:"type:Cursor", icon:"[SKIN]text_code.gif",
                                     title:"Cursor"},
                                    {id:"411", ref:"type:ImageStyle", icon:"[SKIN]text_code.gif",
                                     title:"ImageStyle"},
                                    {id:"412", ref:"type:DrawPosition", icon:"[SKIN]text_code.gif",
                                     title:"DrawPosition"},
                                    {id:"413", ref:"type:CSSStyleName", icon:"[SKIN]text_code.gif",
                                     title:"CSSStyleName"},
                                    {id:"414", ref:"type:PercentBoxModel", icon:"[SKIN]text_code.gif",
                                     title:"PercentBoxModel"},
                                    {id:"415", ref:"type:SCImgURL", icon:"[SKIN]text_code.gif",
                                     title:"SCImgURL"},
                                    {id:"416", ref:"type:DragDataAction", icon:"[SKIN]text_code.gif",
                                     title:"DragDataAction"},
                                    {id:"417", ref:"type:dataPath", icon:"[SKIN]text_code.gif",
                                     title:"dataPath"},
                                    {id:"418", ref:"type:JSONDateFormat", icon:"[SKIN]text_code.gif",
                                     title:"JSONDateFormat"},
                                    {id:"419", ref:"type:JSONInstanceSerializationMode",
                                     icon:"[SKIN]text_code.gif", title:"JSONInstanceSerializationMode"},
                                    {id:"420", ref:"type:JSONCircularReferenceMode",
                                     icon:"[SKIN]text_code.gif", title:"JSONCircularReferenceMode"},
                                    {id:"421", ref:"type:AutoTestLocator", icon:"[SKIN]text_code.gif",
                                     title:"AutoTestLocator"},
                                    {id:"422", ref:"type:LocatorStrategy", icon:"[SKIN]text_code.gif",
                                     title:"LocatorStrategy"},
                                    {id:"423", ref:"type:LocatorTypeStrategy",
                                     icon:"[SKIN]text_code.gif", title:"LocatorTypeStrategy"},
                                    {id:"424", ref:"type:DialogButtons", icon:"[SKIN]text_code.gif",
                                     title:"DialogButtons"},
                                    {id:"425", ref:"type:EdgeSizes", icon:"[SKIN]text_code.gif",
                                     title:"EdgeSizes"},
                                    {id:"426", ref:"type:TabTitleEditEvent",
                                     icon:"[SKIN]text_code.gif", title:"TabTitleEditEvent"},
                                    {id:"427", ref:"type:AnimationAcceleration",
                                     icon:"[SKIN]text_code.gif", title:"AnimationAcceleration"},
                                    {id:"428", ref:"type:animateShowEffectId",
                                     icon:"[SKIN]text_code.gif", title:"animateShowEffectId"},
                                    {id:"429", ref:"type:State", icon:"[SKIN]text_code.gif",
                                     title:"State"},
                                    {id:"430", ref:"type:SelectionType", icon:"[SKIN]text_code.gif",
                                     title:"SelectionType"},
                                    {id:"431", ref:"type:Selected", icon:"[SKIN]text_code.gif",
                                     title:"Selected"},
                                    {id:"432", ref:"type:Orientation", icon:"[SKIN]text_code.gif",
                                     title:"Orientation"},
                                    {id:"433", ref:"type:LayoutPolicy", icon:"[SKIN]text_code.gif",
                                     title:"LayoutPolicy"},
                                    {id:"434", ref:"type:LayoutResizeBarPolicy",
                                     icon:"[SKIN]text_code.gif", title:"LayoutResizeBarPolicy"},
                                    {id:"435", ref:"type:VisibilityMode", icon:"[SKIN]text_code.gif",
                                     title:"VisibilityMode"},
                                    {id:"436", ref:"type:SummaryFunction", icon:"[SKIN]text_code.gif",
                                     title:"SummaryFunction"},
                                    {id:"437", ref:"type:NavigationDirection",
                                     icon:"[SKIN]text_code.gif", title:"NavigationDirection"},
                                    {id:"438", ref:"type:ControlName", icon:"[SKIN]text_code.gif",
                                     title:"ControlName"}
                                ]
                            }
                        ]
                    },
                    {
                        id:"84",
                        title:"Client Bridges",
                        children:[
                            {id:"85", ref:"class:BrowserPlugin", icon:"[SKIN]text_code_javascript.gif",
                             title:"BrowserPlugin"},
                            {id:"86", ref:"class:Applet", icon:"[SKIN]text_code_javascript.gif",
                             title:"Applet"},
                            {id:"87", ref:"class:Flashlet", icon:"[SKIN]text_code_javascript.gif",
                             title:"Flashlet"},
                            {id:"88", ref:"class:SVG", icon:"[SKIN]text_code_javascript.gif",
                             title:"SVG"},
                            {id:"89", ref:"class:ActiveXControl",
                             icon:"[SKIN]text_code_javascript.gif", title:"ActiveXControl"}
                        ]
                    },
                    {
                        id:"190",
                        title:"Calendar",
                        children:[
                            {id:"191", ref:"class:Calendar", icon:"[SKIN]text_code_javascript.gif",
                             title:"Calendar"},
                            {id:"192", ref:"object:CalendarEvent",
                             icon:"[SKIN]text_code_javascript.gif", title:"CalendarEvent"}
                        ]
                    },
                    {
                        id:"295",
                        title:"Connectors",
                        children:[
                            {id:"296", ref:"class:EBay", icon:"[SKIN]text_code_javascript.gif",
                             title:"EBay"}
                        ]
                    }
                ],
                id:"1"
            },
            {
                id:"javaServerReference",
                isOpen:"true",
                requiresModules:"SCServer",
                title:"Java Server Reference",
                children:[
                    {title:"SmartClient Server Summary", id:"21", icon:"[SKIN]cube_blue.gif",
                     ref:"group:iscServer"},
                    {title:"Server DataSource Integration", id:"22", icon:"[SKIN]cube_blue.gif",
                     ref:"group:serverDataIntegration"},
                    {contentsURL:"[referenceRoot]server/javadoc/index.html", icon:"[SKIN]cup.gif",
                     title:"Javadoc", id:"23"},
                    {
                        icon:"[SKIN]cube_blue.gif",
                        isFolder:true,
                        isOpen:"true",
                        ref:"group:jspTags",
                        title:"SmartClient JSP Tags",
                        id:"24",
                        children:[
                            {id:"51", ref:"group:loadISCTag", icon:"[SKIN]cube_blue.gif",
                             title:"&lt;isomorphic:loadISC&gt;"},
                            {id:"52", ref:"group:loadModulesTag", icon:"[SKIN]cube_blue.gif",
                             title:"&lt;isomorphic:loadModules&gt;"},
                            {id:"53", ref:"group:loadDSTag", icon:"[SKIN]cube_blue.gif",
                             title:"&lt;isomorphic:loadDS&gt;"},
                            {id:"54", ref:"group:loadUITag", icon:"[SKIN]cube_blue.gif",
                             title:"&lt;isomorphic:loadUI&gt;"},
                            {id:"55", ref:"group:xmlTag", icon:"[SKIN]cube_blue.gif",
                             title:"&lt;isomorphic:XML&gt;"},
                            {id:"56", ref:"group:loadXMLSchemaTag", icon:"[SKIN]cube_blue.gif",
                             title:"&lt;isomorphic:loadXMLSchema&gt;"},
                            {id:"57", ref:"group:loadWSDLTag", icon:"[SKIN]cube_blue.gif",
                             title:"&lt;isomorphic:loadWSDL&gt;"},
                            {id:"58", ref:"group:jsStringTag", icon:"[SKIN]cube_blue.gif",
                             title:"&lt;isomorphic:jsString&gt;"},
                            {id:"71", ref:"group:loadDMIStubsTag", icon:"[SKIN]cube_blue.gif",
                             title:"&lt;isomorphic:loadDMIStubs&gt;"}
                        ]
                    }
                ]
            },
            {
                id:"optionalModules",
                isOpen:"false",
                title:"Optional Modules",
                children:[
                    {
                        isFolder:true,
                        isOpen:"false",
                        requiresModules:"Analytics",
                        title:"Analytics",
                        children:[
                            {contentsURL:"[docRoot]resources/Analytics_QuickRef.pdf",
                             icon:"[SKIN]pdf.gif", title:"CubeGrid QuickRef", id:"28"},
                            {
                                id:"90",
                                ref:"class:CubeGrid",
                                icon:"[SKIN]text_code_javascript.gif",
                                title:"CubeGrid",
                                children:[
                                    {id:"91", ref:"class:Facet", icon:"[SKIN]text_code_javascript.gif",
                                     title:"Facet"},
                                    {id:"92", ref:"class:FacetValue",
                                     icon:"[SKIN]text_code_javascript.gif", title:"FacetValue"},
                                    {id:"93", ref:"object:FacetValueMap",
                                     icon:"[SKIN]text_code_javascript.gif", title:"FacetValueMap"},
                                    {id:"94", ref:"object:CellRecord",
                                     icon:"[SKIN]text_code_javascript.gif", title:"CellRecord"}
                                ]
                            },
                            {id:"95", ref:"interface:Chart", icon:"[SKIN]text_code_javascript.gif",
                             title:"Chart"},
                            {id:"96", ref:"class:FusionChart", icon:"[SKIN]text_code_javascript.gif",
                             title:"FusionChart"},
                            {id:"97", ref:"class:FacetChart", icon:"[SKIN]text_code_javascript.gif",
                             title:"FacetChart"}
                        ],
                        id:"25"
                    },
                    {
                        isFolder:true,
                        isOpen:"false",
                        requiresModules:"RealtimeMessaging",
                        title:"Messaging",
                        children:[
                            {contentsURL:"[docRoot]resources/Messaging_QuickRef.pdf",
                             icon:"[SKIN]pdf.gif", id:"Messaging QuickRef",
                             title:"Messaging QuickRef"}
                        ],
                        id:"26"
                    },
                    {
                        isFolder:true,
                        isOpen:"false",
                        requiresModules:"NetworkPerformance",
                        title:"Network Performance",
                        id:"27",
                        icon:"[SKIN]cube_blue.gif",
                        ref:"group:networkPerformance",
                        children:[
                            {id:"81", ref:"group:compression", icon:"[SKIN]cube_blue.gif",
                             title:"Compression"},
                            {id:"82", ref:"group:caching", icon:"[SKIN]cube_blue.gif", title:"Caching"},
                            {id:"83", ref:"group:fileAssembly", icon:"[SKIN]cube_blue.gif",
                             title:"File Assembly"},
                            {id:"297", ref:"class:FileLoader", icon:"[SKIN]text_code_javascript.gif",
                             title:"FileLoader"}
                        ]
                    }
                ]
            }
        ]
    },
    refToID:{"class:HTMLFlow":"183", "type:RPCTransport":"342", "class:HStack":"264", "object:Hilite":"241",
     "class:FacetValue":"92", "class:MenuButton":"212", "class:BrowserPlugin":"85",
     "class:LinkItem":"123", "object:Criterion":"167", "type:LayoutResizeBarPolicy":"434",
     "type:SortArrow":"354", "type:MenuFieldID":"378", "type:CriteriaCombineOperator":"339",
     "class:GroupingMessages":"290", "group:loadWSDLTag":"57", "type:AutoFitEvent":"362",
     "type:listGridViewState":"374", "class:HTMLPane":"184", "type:VelocityExpression":"336",
     "class:MiniDateRangeItem":"155", "type:AutoFitWidthApproach":"363",
     "class:DataSourceField":"158", "type:listGridSelectedState":"372", "class:UploadItem":"137",
     "class:TimeItem":"135", "type:LineBreakStyle":"333", "type:ViewName":"349", "class:CubeGrid":"90",
     "class:ViewLoader":"182", "class:SVG":"88", "class:TileGrid":"216", "type:State":"429",
     "class:Selection":"200", "type:ListGridEditEvent":"367", "type:TileLayoutPolicy":"379",
     "type:OperatorValueType":"337", "type:RecordComponentPoolingMode":"366",
     "type:RecordLayout":"381", "class:WebService":"170", "group:fileAssembly":"83",
     "type:AnimationAcceleration":"427", "group:operations":"62", "class:Log":"233",
     "class:DataPathItem":"150", "type:FieldType":"328", "type:Direction":"409",
     "object:CellRecord":"94", "class:Offline":"180", "group:mobileDevelopment":"29",
     "type:LogPriority":"391", "class:DataView":"179", "type:RecordSummaryFunction":"340",
     "type:PromptStyle":"343", "class:XJSONDataSource":"169", "class:FormulaBuilder":"224",
     "class:VStack":"265", "class:isc":"98", "group:dataSourceDeclaration":"37",
     "type:Positioning":"403", "type:DateItemSelectorFormat":"314", "type:CriteriaPolicy":"346",
     "type:ObjectLiteral":"387", "group:platformDependencies":"60", "type:listGridSortState":"373",
     "type:DisplayNodeType":"350", "class:Tree":"196", "group:loadUITag":"54",
     "class:TileLayout":"214", "type:treeGridViewState":"377", "object:FacetValueMap":"93",
     "type:RelativeDate":"317", "type:DSCallback":"329", "type:ValueMap":"326",
     "object:groupNode":"206", "type:PageEvent":"397", "object:TestFunctionResult":"243",
     "class:RowSpacerItem":"131", "class:ScrollThumb":"285", "class:ResultSet":"177",
     "class:ColumnTree":"219", "class:ResultTree":"178", "class:Class":"228", "class:Validator":"107",
     "class:Slider":"102", "type:FormMethod":"305", "interface:List":"195", "class:ViewFileItem":"149",
     "object:Number":"230", "type:CSSStyleName":"413", "type:XMLElement":"321", "type:Callback":"385",
     "type:EmbeddedPosition":"365", "group:springIntegration":"8", "group:gaeIntegration":"43",
     "type:listGridFieldState":"370", "type:XMLDocument":"320", "group:loadDMIStubsTag":"71",
     "class:DSResponse":"160", "group:wsdlBinding":"59", "type:AutoSelectionModel":"301",
     "class:NativeCheckboxItem":"118", "class:PasswordItem":"124", "class:MultiFileItem":"139",
     "type:EscapeKeyEditAction":"358", "class:MathFunction":"242", "class:Img":"270",
     "type:RelativeDateString":"318", "class:StaticTextItem":"122", "class:FilterBuilder":"189",
     "object:ImgProperties":"239", "type:TabTitleEditEvent":"426", "class:ActiveXControl":"89",
     "group:treeDataBinding":"72", "type:NavigationDirection":"437",
     "group:clientOnlyDataSources":"47", "type:SortDirection":"392", "object:DateRange":"153",
     "class:SliderItem":"142", "type:Encoding":"306", "group:debugging":"4",
     "type:FieldAppearance":"311", "type:ImageStyle":"411", "object:Record":"157",
     "class:IPickTreeItem":"145", "group:dateFormatAndStorage":"76", "class:Hover":"245",
     "group:hibernateIntegration":"9", "type:ChartType":"304", "type:AutoChild":"388",
     "group:iscInstall":"5", "type:OperatorId":"338", "class:DatabaseBrowser":"193",
     "group:sqlVsJPA":"66", "class:ToolStripResizer":"289",
     "group:featureExplorerOverview":"featureExplorerOverview", "type:TimeUnit":"319",
     "object:isA":"226", "class:EBay":"296", "class:HibernateBrowser":"194", "group:editing":"74",
     "class:TabBar":"250", "type:SendMethod":"395", "type:Visibility":"404",
     "type:DragDataAction":"416", "class:Progressbar":"273", "group:strutsIntegration":"11",
     "object:CalendarEvent":"192", "group:formLayout":"30", "class:ColorItem":"143",
     "type:NavigationMode":"382", "class:NavigationBar":"292", "class:TableView":"220",
     "type:FetchMode":"345", "class:TextItem":"110", "group:javaModuleDependencies":"41",
     "class:AutoFitTextAreaItem":"134", "group:clientDataIntegration":"50",
     "class:SelectOtherItem":"116", "group:loadDSTag":"53", "class:TreeGrid":"197",
     "group:loadModulesTag":"52", "type:EditCompletionEvent":"359", "object:Browser":"99",
     "class:Timer":"236", "class:PortalLayout":"252", "object:Array":"229", "group:loadISCTag":"51",
     "class:TabSet":"249", "class:ColorPicker":"148", "object:TreeGridField":"209",
     "class:FlowLayout":"215", "class:ImgButton":"275", "type:CharacterCasing":"312",
     "class:XMLTools":"156", "group:keyboardEvents":"77", "class:DateItem":"128",
     "class:DataSource":"36", "type:dataPath":"417", "class:Operators":"187",
     "class:MultiSortPanel":"256", "interface:Chart":"95", "type:ValidatorType":"310",
     "group:loadXMLSchemaTag":"56", "class:Window":"251", "type:JSONCircularReferenceMode":"420",
     "type:DragTrackerMode":"368", "type:Properties":"386", "class:Time":"234",
     "type:TitleOrientation":"307", "class:BlurbItem":"111", "type:RowEndEditAction":"356",
     "class:Toolbar":"274", "class:SubmitItem":"132", "interface:DataBoundComponent":"240",
     "class:Dialog":"254", "class:CheckboxItem":"117", "group:jpaIntegration":"42",
     "class:GridRenderer":"204", "class:LoginDialog":"255", "class:WSRequest":"172",
     "group:iscServer":"21", "group:componentXML":"12", "group:jspTags":"24", "class:StretchImg":"271",
     "type:ListGridFieldType":"361", "class:Splitbar":"286", "class:VLayout":"263",
     "group:stringMethods":"75", "class:WSDataSource":"185", "class:HLayout":"262",
     "class:DOMGrid":"221", "type:LayoutPolicy":"433", "class:CanvasItem":"109",
     "object:DetailViewerRecord":"202", "group:clientServerIntegration":"2", "type:RPCCallback":"341",
     "class:ToolbarItem":"136", "type:DragAppearance":"398", "class:EventHandler":"237",
     "class:HeaderItem":"119", "group:upload":"34", "class:SectionStack":"279", "class:Page":"235",
     "type:EnterKeyEditAction":"357", "group:sqlSettings":"46", "class:DateRangeDialog":"154",
     "type:treeGridOpenState":"376", "type:FormItemType":"308", "type:ExportFormat":"331",
     "type:SelectionStyle":"353", "class:JSONEncoder":"247", "type:DSProtocol":"335",
     "object:Operator":"168", "class:RichTextItem":"299", "group:networkPerformance":"27",
     "class:ValuesManager":"147", "type:PageOrientation":"394", "group:dataSourceLocalization":"39",
     "group:metadataImport":"68", "type:Orientation":"432", "group:dataBoundComponentMethods":"79",
     "object:SectionStackSection":"280", "class:ImgSplitbar":"287", "class:SelectItem":"115",
     "class:DetailViewer":"201", "class:PickTreeItem":"144", "class:DateTimeItem":"129",
     "class:OperationBinding":"163", "class:DateChooser":"101",
     "group:featuresCustomPersistence":"65", "type:ExpansionMode":"369", "type:SCImgURL":"415",
     "class:ImgTab":"248", "class:FormItem":"105", "type:TextMatchStyle":"330", "class:Layout":"261",
     "type:DateInputFormat":"389", "object:DetailViewerField":"203",
     "type:JSONInstanceSerializationMode":"419", "object:validatorDefinition":"108",
     "type:PercentBoxModel":"414", "type:DialogButtons":"424", "type:VerticalAlignment":"407",
     "class:ImgSectionHeader":"282", "object:animationShowEffect":"259",
     "type:animateShowEffectId":"428", "object:TileRecord":"217", "type:SCClassName":"384",
     "class:MultiSortDialog":"257", "group:sqlDataSource":"44", "type:GroupStartOpen":"360",
     "class:StatefulCanvas":"260", "class:Mail":"165", "type:TEXTAREA_WRAP":"315",
     "class:SplitPane":"294", "object:DSRequestModifier":"164", "class:RichTextEditor":"298",
     "class:SummaryBuilder":"225", "object:TreeNode":"199", "object:ListGridRecord":"205",
     "type:TopOperatorAppearance":"348", "class:FacetChart":"97", "type:Alignment":"406",
     "type:Cursor":"410", "class:ResetItem":"127", "type:AutoTestLocator":"421", "type:Overflow":"405",
     "type:Object":"383", "class:DSRequest":"161", "group:dataSourceOperations":"63",
     "class:FilterClause":"188", "type:HoverMode":"375", "class:SpacerItem":"130",
     "group:serverDataSourceImplementation":"48", "type:ExportDisplay":"332", "type:TableMode":"380",
     "type:DateDisplayFormat":"390", "group:criteriaEditing":"31", "class:SchemaSet":"171",
     "object:AdvancedCriteria":"166", "group:dmiOverview":"69", "class:String":"232",
     "interface:PickList":"113", "type:KeyName":"400", "type:DSServerType":"324",
     "class:SpinnerItem":"141", "class:EdgedCanvas":"244", "type:FormItemBaseStyle":"309",
     "type:FireStyle":"396", "group:smartArchitecture":"3", "group:visualBuilder":"6",
     "type:Selected":"431", "class:Flashlet":"87", "class:FileItem":"33", "type:LoadState":"351",
     "type:SelectionBoundary":"302", "type:Criteria":"344", "class:ComboBoxItem":"138",
     "class:MenuBar":"222", "type:DrawPosition":"412", "type:DragIntersectStyle":"399",
     "class:RadioGroupItem":"125", "class:SearchForm":"146", "object:FormItemEventInfo":"104",
     "type:ControlName":"438", "group:caching":"82", "class:JSON":"246",
     "type:LocatorTypeStrategy":"423", "class:RPCResponse":"175", "type:SelectionAppearance":"371",
     "group:i18n":"38", "class:LayoutSpacer":"266", "type:LogicalOperator":"347",
     "class:RPCRequest":"174", "class:NavigationButton":"293", "class:Scrollbar":"283",
     "class:SimpleTile":"218", "object:ListGridField":"207", "class:Button":"267",
     "type:VisibilityMode":"435", "class:DynamicForm":"103", "class:RestDataSource":"186",
     "class:ButtonItem":"112", "class:Menu":"210", "type:AutoFitIconFieldType":"364",
     "group:xmlTag":"55", "class:Facet":"91", "class:Applet":"86", "class:SectionHeader":"281",
     "object:MenuItem":"211", "group:jsfIntegration":"10", "class:Date":"231",
     "type:EnumTranslateStrategy":"325", "type:Side":"408", "class:SimpleType":"291",
     "type:MultipleAppearance":"313", "class:MultiFilePicker":"140", "group:nonJavaBackend":"7",
     "type:PanelHeaderPlacement":"316", "class:ToolStripSeparator":"278",
     "group:componentSchema":"35", "group:adminConsole":"45", "type:JSONDateFormat":"418",
     "class:SectionItem":"120", "group:applicationDeclaration":"70", "class:RPCManager":"173",
     "type:LocatorStrategy":"422", "class:RadioItem":"126", "type:EdgeSizes":"425",
     "type:ReorderPosition":"355", "object:Tab":"258", "group:Prompting":"80",
     "object:SerializationContext":"159", "object:HeaderSpan":"208", "type:ValidationMode":"334",
     "object:FormItemIcon":"106", "class:DateRangeItem":"152", "class:HiddenItem":"121",
     "class:DMI":"176", "group:skinning":"78", "type:TreeModelType":"352", "class:Calendar":"191",
     "class:StretchImgButton":"276", "type:SummaryFunction":"436", "class:ToolStrip":"277",
     "class:RelativeDateItem":"151", "type:DSOperationType":"322", "group:serverDataIntegration":"22",
     "group:servletDetails":"40", "class:FileLoader":"297", "type:SelectionType":"430",
     "class:ListGrid":"73", "group:compression":"81", "class:History":"100", "type:Axis":"303",
     "type:HashAlgorithm":"327", "type:KeyIdentifier":"401", "class:AutoFitButton":"268",
     "type:timeFormatter":"393", "group:writeCustomDataSource":"64", "class:ServerObject":"162",
     "group:jsStringTag":"58", "class:Label":"272", "type:DSDataFormat":"323",
     "object:ClassFactory":"227", "class:CellSelection":"223", "class:PickListMenu":"114",
     "class:Portlet":"253", "class:IMenuButton":"213", "class:Canvas":"238",
     "class:PropertySheet":"181", "type:ClickMaskMode":"402", "class:FusionChart":"96",
     "group:relogin":"61", "class:IButton":"269", "class:Snapbar":"288", "class:TextAreaItem":"133"}
})
